### ISSUE TITLE
Crash with QR code plugin

### ISSUE THREAD

**Issue by adnanfajr** [YOURLS/404-if-not-found#1]
I am using QR code plugin that adds .qr extension at the end of the url. But when I activate this 404 plugin, when I want to generate qr by adding .qr at the url it responses with 404 page. How to solve that issue?

**Comment by ozh** [comment]
Ask the QR plugin author to either use an earlier hook than, I presume, `redirect_keyword_not_found`, or, better, to use this hook with a higher priority
