### ISSUE TITLE
No plugin specified, or not a valid plugin

### ISSUE THREAD

**Issue by arladmin** [YOURLS/404-if-not-found#5]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.2

### Description

When i try to activate the plugin, i see the error message:
![image](https://user-images.githubusercontent.com/64059154/226075528-520e22cd-d8f7-49db-ac0a-3af9debf5236.png)

**Comment by ozh** [comment]
Cannot reproduce, the plugin activates fine. You did something wrong, probably when uploading or editing the plugin file.
